MVCEmployes/Models/Employes.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace MVCEmployes.Models
{
    public class Employes : IGeneralField , IEmplId, IModify
    {
        [Key]
        public int id { get; set; }

        public string FirstName { get; set; }
        public string LastName { get; set; }

        public DateTime? DateUpdate { get; set; }

    }

    public interface IEmplId
    {
        int id { get; set; }
    }
    //основная форма
    public interface IGeneralField : IEmplId
    {
        string FirstName { get; set; }
        string LastName { get; set; }        
    }

    public interface IModify : IEmplId
    {
        DateTime? DateUpdate { get; set; }
    }
}

MVCEmployes/Models/ErrorViewModel.cs
using System;

namespace MVCEmployes.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVCEmployes/Components/EmplFormViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MVCEmployes.Core;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCEmployes.Components
{
    public class EmplFormViewComponent : ViewComponent
    {
        IEmployesRepository _empl;

        public EmplFormViewComponent(IEmployesRepository empl)
        {
            _empl = empl;
        }
        public IViewComponentResult Invoke(int  id)
        {
            EditFormEmployee form;
            if (id == 0)
            {
                form = new EditFormEmployee { edit_id = 0 };
            }
            else
            {
                var empl = _empl.GetEmployee(id);

                form = new EditFormEmployee
                {
                    edit_id = empl.id,
                    edit_FirstName = empl.FirstName,
                    edit_LastName = empl.LastName
                };
            }
            return View(form);
        }
    }
}

MVCEmployes/Components/EmployeeListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MVCEmployes.Core;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCEmployes.Components
{
    public class EmployeeListViewComponent: ViewComponent
    {
        IEmployesRepository _empl;

        public EmployeeListViewComponent(IEmployesRepository empl)
        {
            _empl =empl;
        }
        public IViewComponentResult Invoke()
        {

            return View(_empl.GetEmployes());
        }
    }
}

MVCEmployes/Controllers/EmployesController.cs
using Microsoft.AspNetCore.Mvc;
using MVCEmployes.Core;
using MVCEmployes.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCEmployes.Controllers
{
    public class EmployesController : Controller
    {
        IEmployesRepository _empl;
        public EmployesController(IEmployesRepository empl)
        {
            _empl = empl;
        }
        public IActionResult Index()
        {
            var model_list = _empl.GetEmployes();
            return View(model_list);
        }

        public IActionResult DebugFormEmpl()
        {
            return View();
        }
        public IActionResult EmployeeList()
        {
            return ViewComponent("EmployeeList");
        }

        public IActionResult EmplForm(int id)
        {
            return ViewComponent("EmplForm", new { id = id });
        }

        [HttpPost]
        public JsonResult SubmitEmpl(EditFormEmployee empl)
        {

            // если есть лшибки - возвращаем false
            if (!ModelState.IsValid)
                return Json(false);

            try
            {
                Employes model = new Employes
                {
                    id = empl.edit_id,
                    FirstName = empl.edit_FirstName,
                    LastName = empl.edit_LastName
                };

                return Json(_empl.SubmitEmployee(model));
            }
            catch
            {
                return Json(-1);
            }
        }

        [HttpPost]
        public JsonResult DeleteEmpl(int id_empl)
        {
            try
            {
                _empl.RemoveEmployee(id_empl);
                return Json(0);
            }
            catch
            {
                return Json(-1);
            }
        }
    }
}

MVCEmployes/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MVCEmployes.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MVCEmployes.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVCEmployes/Views/Employes/Components/EmplForm/Default.cshtml
@model MVCEmployes.EditFormEmployee

<form data-ajax='true' id='formEmpl' method='post'>

    @Html.Hidden("edit_id", Model.edit_id)

    <div class="form-group">
        <label for="edit_FirstName">Имя</label>
        <input type="text" class="form-control" id="edit_FirstName" name="edit_FirstName" placeholder="Имя" value="@Model.edit_FirstName" required>
        <div class="invalid-feedback">
            Please provide a valid city.
        </div>
    </div>
    <div class="form-group">

    </div>
    <div class="form-row">
        <div class="col-md-6 mb-3">
            <label for="edit_LastName">Фамилия</label>
            <input type="text" class="form-control" id="edit_LastName" name="edit_LastName" placeholder="Фамилия" value="@Model.edit_LastName" required>
            <div class="invalid-feedback">
                Please provide a valid city.
            </div>
        </div>
    </div>
    <button class="btn btn-primary" onclick='submitEmpl()' type="submit">Submit</button>

</form>

MVCEmployes/Views/Employes/Components/EmployeeList/Default.cshtml
@model IEnumerable<MVCEmployes.Models.Employes>

    <h4>Список сотрудников:</h4>

    <table id="EmplTable" class="table table-bordered">
        <thead>
            <tr>
                <th scope="col">

                </th>

                <th scope="col">
                    Имя
                </th>
                <th scope="col">
                    Фамилия
                </th>
                <th scope="col">
                    Время редактирования
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var empl in Model)
            {
            <tr>
                <td>

                    <button type='button' class='btn btn-link' onclick='openDetalies(@empl.id)'>Update</button>
                    <button type='button' class='btn btn-link' onclick='delete_empl(@empl.id)'>Delete</button>
                </td>
                <td>
                    @empl.FirstName
                </td>
                <td>
                    @empl.LastName
                </td>
                <td>
                    @empl.DateUpdate
                </td>
            </tr>
                }


</tbody>
    </table>

MVCEmployes/Views/Employes/DebugFormEmpl.cshtml
<script src="~/js/Employee.js?version=1"></script>


<div id="divform">
    @await Component.InvokeAsync("EmplForm", new { id = 1 })
</div>

MVCEmployes/Views/Employes/Index.cshtml
<script src="~/js/Employee.js?version=1"></script>

<button type="button" class="btn btn-link" onclick="openDetalies(0);">Добавить</button>


<div id="table_empls">
    @await Component.InvokeAsync("EmployeeList")
</div>


@{ 
    Html.RenderPartial("~/Views/Employes/ModalCreate.cshtml"); 
}

MVCEmployes/Views/Employes/ModalCreate.cshtml
<div class="modal fade" id="myModalEmplForm">
    <div class="modal-dialog  modal-dialog-centered" role="document" style="width: 1200px;">
        <div class="modal-content" style="background-color: #EDF3F4;">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                
            </div>
            <h4 class="modal-title">Редактирование Информации</h4>
            <div class="modal-body" id="EmployeeFormDiv">

            </div>
        </div>
    </div>
</div>

MVCEmployes/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MVCEmployes/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCEmployes</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVCEmployes</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MVCEmployes - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>